/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/chords/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List all chords. */
    get: operations["chords_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chords/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve a single chord by ID. */
    get: operations["chords_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lessons/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List all published lessons. */
    get: operations["lessons_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lessons/{uuid}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve a single published lesson by UUID. */
    get: operations["lessons_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List all published courses. */
    get: operations["courses_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{uuid}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve a single published course by UUID. */
    get: operations["courses_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/announcements/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List all published announcements. */
    get: operations["announcements_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/announcements/{uuid}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve a single published announcement by UUID. */
    get: operations["announcements_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Serializer for announcement detail. */
    AnnouncementDetail: {
      /** Format: uuid */
      readonly uuid: string;
      /** Заголовок */
      title: string;
      slug: string;
      /** Содержание */
      content: string;
      /**
       * Версия продукта
       * @description Например: 1.2.0
       */
      product_version?: string;
      /**
       * Дата создания
       * Format: date-time
       */
      readonly created_at: string;
      /**
       * Дата обновления
       * Format: date-time
       */
      readonly updated_at: string;
    };
    /** @description Serializer for announcements list. */
    AnnouncementsList: {
      /** Format: uuid */
      readonly uuid: string;
      /** Заголовок */
      title: string;
      slug: string;
      /**
       * Версия продукта
       * @description Например: 1.2.0
       */
      product_version?: string;
      /**
       * Дата-время публикации
       * Format: date-time
       */
      published_at?: string | null;
    };
    /** @description Serializer for chord detail. */
    ChordDetail: {
      readonly id: number;
      /** Название */
      title: string;
      /** Музыкальное название */
      musical_title: string;
      /** Порядок отображения */
      order_in_note?: number;
      /** С какого лада начинается */
      start_fret?: number;
      /** Есть барре? */
      has_barre?: boolean;
      readonly positions: components["schemas"]["ChordPosition"][];
    };
    /** @description Serializer for one string position. */
    ChordPosition: {
      /** Номер струны */
      string_number: number;
      /**
       * На каком ладу зажата
       * @description 0 - открыта, -1 - заглушена
       */
      fret: number;
      /** Каким пальцем зажата */
      finger: number;
    };
    /** @description Serializer for chords list. */
    ChordsList: {
      readonly id: number;
      /** Название */
      title: string;
      /** Музыкальное название */
      musical_title: string;
      readonly positions: components["schemas"]["ChordPosition"][];
    };
    /** @description Serializer for course detail. */
    CourseDetail: {
      /** Format: uuid */
      readonly uuid: string;
      /** Название */
      title: string;
      /** Описание */
      description?: string;
      /**
       * Дата создания
       * Format: date-time
       */
      readonly created_at: string;
      /**
       * Дата обновления
       * Format: date-time
       */
      readonly updated_at: string;
      lessons: components["schemas"]["CourseLessonDetail"][];
    };
    /** @description Serializer for lesson within course detail. */
    CourseLessonDetail: {
      order: number;
      lesson: components["schemas"]["LessonsList"];
    };
    /** @description Serializer for courses list. */
    CoursesList: {
      /** Format: uuid */
      readonly uuid: string;
      /** Название */
      title: string;
      /** Описание */
      description?: string;
      readonly lessons_count: number;
    };
    /** @description Output  serializer for an image scheme. */
    ImageScheme: {
      readonly id: number;
      /** Надпись */
      inscription?: string;
      /**
       * Изображение
       * Format: uri
       */
      image: string;
      /** Высота */
      height?: number | null;
      /** Ширина */
      width?: number | null;
    };
    /** @description Serializer for lesson detail. */
    LessonDetail: {
      /** Format: uuid */
      readonly uuid: string;
      /** Название */
      title: string;
      /**
       * Описание
       * @description Краткое описание содержания урока
       */
      description?: string;
      /**
       * Видео
       * Format: uri
       * @description Ссылка на видео урока
       */
      video_url: string;
      /**
       * Длительность (сек)
       * @description Общая длительность урока в секундах
       */
      duration?: number;
      readonly songs: components["schemas"]["SongDetail"][];
      readonly addition_lessons: components["schemas"]["LessonsList"][];
    };
    /** @description Serializer for lessons list. */
    LessonsList: {
      /** Format: uuid */
      readonly uuid: string;
      /** Название */
      title: string;
      /**
       * Описание
       * @description Краткое описание содержания урока
       */
      description?: string;
      /**
       * Видео
       * Format: uri
       * @description Ссылка на видео урока
       */
      video_url: string;
      readonly songs: components["schemas"]["SongList"][];
    };
    /** @description Song detail serializer. */
    SongDetail: {
      readonly id: number;
      /** Название */
      title: string;
      /**
       * Текст песни
       * @description С аккордами и переносами строк
       */
      text: string;
      /** Метроном */
      metronome?: number;
      readonly schemes: components["schemas"]["ImageScheme"][];
      readonly chords: components["schemas"]["ChordDetail"][];
    };
    /** @description Serializer for list of songs. */
    SongList: {
      readonly id: number;
      /** Название */
      title: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  chords_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChordsList"][];
        };
      };
    };
  };
  chords_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChordDetail"];
        };
      };
    };
  };
  lessons_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LessonsList"][];
        };
      };
    };
  };
  lessons_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LessonDetail"];
        };
      };
    };
  };
  courses_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoursesList"][];
        };
      };
    };
  };
  courses_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDetail"];
        };
      };
    };
  };
  announcements_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnnouncementsList"][];
        };
      };
    };
  };
  announcements_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnnouncementDetail"];
        };
      };
    };
  };
}
